Don't include declarations in usages (fixes #629).
antlr/intellij-plugin-v4 pull request #649
Opened 2023-07-07 12:45 UTC by ris58h

2023-07-19 09:47 UTC, ris58h commented
@bjansen Sorry for bothering you. I don't know who should I ping to approve the workflow.

2023-09-13 20:17 UTC, bjansen commented
I'll look into it this week, sorry for the delay

2023-09-14 11:35 UTC, bjansen requested changes

2023-09-14 11:35 UTC, bjansen commented on src/main/java/org/antlr/intellij/plugin/ANTLRv4ASTFactory.java
> +		ruleElementTypeToPsiFactory.put(ANTLRv4TokenTypes.RULE_ELEMENT_TYPES.get(ANTLRv4Parser.RULE_tokensSpec), TokensSpecNode.Factory.INSTANCE);
I'm not sure we need this, token definitions already have a parent of type `TokenSpecNode`:
<img width="912" alt="image" src="https://github.com/antlr/intellij-plugin-v4/assets/281528/9eb96e69-e26c-4fe5-8433-bdb0e3d566c1">
So using `getParent() instanceof TokenSpecNode` should be enough.

2023-09-14 11:35 UTC, bjansen commented on src/main/java/org/antlr/intellij/plugin/psi/LexerRuleRefNode.java
> +	protected boolean isDeclaration() {
I would have kept `getReference()` here and simply add this snippet:
```
		if (getParent() instanceof LexerRuleSpecNode || getParent() instanceof TokenSpecNode) {
			// A declaration doesn't need to reference itself
			return null;
		}
```

(same in `ParserRuleRefNode`)

2023-09-14 13:27 UTC, ris58h commented
@bjansen I've done the requested changes.

2023-09-14 17:26 UTC, merged

2023-09-14 17:26 UTC, bjansen commented
Thanks for the contribution!